words = (
    "Aardvark", "Aardwolf", "Albatross", "Alligator", "Alpaca", "Anteater", "Antelope", "Ape", "Armadillo", "Donkey",
    "Baboon", "Badger", "Barracuda", "Bat", "Bear", "Beaver", "Bee", "Bison", "Boar", "Buffalo",
    "Butterfly", "Camel", "Capybara", "Caribou", "Cassowary", "Cat", "Caterpillar", "Cattle", "Chameleon", "Cheetah",
    "Chimpanzee", "Chinchilla", "Chipmunk", "Clam", "Cobra", "Cockroach", "Cod", "Condor", "Cougar", "Cow",
    "Crab", "Crane", "Crocodile", "Crow", "Curlew", "Deer", "Dinosaur", "Dog", "Dolphin", "Donkey",
    "Dove", "Dragonfly", "Duck", "Dugong", "Eagle", "Echidna", "Eel", "Elephant", "Elk", "Emu",
    "Falcon", "Ferret", "Finch", "Fish", "Flamingo", "Fly", "Fox", "Frog", "Gazelle", "Giraffe",
    "Goat", "Goldfish", "Goose", "Gorilla", "Grasshopper", "Grouse", "Guinea Pig", "Gull", "Hawk", "Hedgehog",
    "Heron", "Herring", "Horse", "Human", "Hummingbird", "Hyena", "Ibex", "Iguana", "Impala", "Indri",
    "Insect", "Jackal", "Jaguar", "Jellyfish", "Kangaroo", "Kingfisher", "Koala", "Kookaburra", "Kouprey", "Kudu",
    "Lamprey", "Land Snail", "Lapwing", "Lark", "Lemur", "Leopard", "Lion", "Lizard", "Llama", "Lobster",
    "Locust", "Loris", "Louse", "Lyrebird", "Macaw", "Magpie", "Mammal", "Manatee", "Mandrill", "Mantis",
    "Manticore", "Marten", "Meerkat", "Mink", "Mole", "Mongoose", "Monkey", "Moose", "Mosquito", "Mouse",
    "Mule", "Musk Ox", "Narwhal", "Newt", "Nightingale", "Octopus", "Okapi", "Opossum", "Orangutan", "Orca",
    "Ostrich", "Otter", "Owl", "Ox", "Panda", "Pangolin", "Panther", "Parakeet", "Parrot", "Partridge",
    "Peacock", "Peafowl", "Pelican", "Penguin", "Pheasant", "Pig", "Pigeon", "Pike", "Piranha", "Platypus",
    "Polar Bear", "Pony", "Porcupine", "Porpoise", "Possum", "Prairie Dog", "Primate", "Pronghorn", "Puma", "Python",
    "Quail", "Quelea", "Queen Alexandra's Birdwing", "Rabbit", "Raccoon", "Rattlesnake", "Raven", "Red Panda",
    "Reindeer", "Rhinoceros", "Right Whale", "Roadrunner", "Robin", "Rook", "Rooster", "Rorqual", "Roundworm",
    "Sable", "Salamander", "Salmon", "Scorpion", "Sea Horse", "Sea Lion", "Sea Turtle", "Sea Urchin", "Seal",
    "Shark", "Sheep", "Shrew", "Shrimp", "Skunk", "Sloth", "Slug", "Snail", "Snake", "Spider",
    "Squid", "Squirrel", "Starfish", "Stingray", "Stoat", "Stork", "Swan", "Tapir", "Tarsier", "Tardigrade",
    "Teal", "Termite", "Tiger", "Toad", "Tortoise", "Toucan", "Trout", "Turkey", "Turtle", "Vulture",
    "Wallaby", "Walrus", "Warthog", "Wasp", "Water Buffalo", "Watermelon", "Weasel", "Whale", "Whiptail",
    "White-tailed Deer", "Wild Boar", "Wolf", "Wolverine", "Wombat", "Woodpecker", "Worm", "Wren", "Yak", "Zebra"
)